/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/alien.gltf
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Alien = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models//alien.gltf");
  const { actions, names } = useAnimations(animations, group);
  console.log(names);
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Ch44">
            <skinnedMesh
              castShadow
              name="Mesh"
              geometry={nodes.Mesh.geometry}
              material={materials.Ch44_Body}
              skeleton={nodes.Mesh.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={materials.Ch44_body1}
              skeleton={nodes.Mesh_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/alien.gltf");

export default Alien;
